version: "3.9"

services:
  socket-server:
    container_name: socket-server
    build:
      context: .
      dockerfile: ./Dockerfile
      # target: appBuilder
    env_file:
      - .env
    restart: always
    ports:
      - 1234:1234
    expose:
      - "1234"
networks:
  default:
    name: odin_master_network
    external: true